# Deployment object
deployment:
  enabled: true
  name: webserver
  namespace: default
  replicas: 3
  appName: webserver
  role: api
  containerName: landing-page
  imageRepository: lucostus/landing-page
  imageTag: latest
  port: 80
# Horizontal Pod Autoscaler
hpa:
  enabled: true
  name: webserver-hpa
  namespace: default
# Service object
service:
  enabled: true
  name: webserver-service
  namespace: default
  appName: webserver
  type: ClusterIP
  servicePort: 80
  targetPort: 80
# Service Account object
serviceAccount:
  enabled: true
  name: webserver-service-account
  namespace: default
# Namespace object
namespace:
  enabled: false
# Ingress 
ingress:
  enabled: true
  name: webserver
  namespace: default
  host: dev.lucostus.at
  path: "/"
  serviceName: webserver-service
  servicePort: 80
